// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: msg_command.proto
// Protobuf C++ Version: 4.25.1

#ifndef GOOGLE_PROTOBUF_INCLUDED_msg_5fcommand_2eproto_2epb_2eh
#define GOOGLE_PROTOBUF_INCLUDED_msg_5fcommand_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/port_def.inc"
#if PROTOBUF_VERSION < 4025000
#error "This file was generated by a newer version of protoc which is"
#error "incompatible with your Protocol Buffer headers. Please update"
#error "your headers."
#endif  // PROTOBUF_VERSION

#if 4025001 < PROTOBUF_MIN_PROTOC_VERSION
#error "This file was generated by an older version of protoc which is"
#error "incompatible with your Protocol Buffer headers. Please"
#error "regenerate this file with a newer version of protoc."
#endif  // PROTOBUF_MIN_PROTOC_VERSION
#include "google/protobuf/port_undef.inc"
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
#include "msg_enum.pb.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_msg_5fcommand_2eproto

namespace google {
namespace protobuf {
namespace internal {
class AnyMetadata;
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_msg_5fcommand_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_msg_5fcommand_2eproto;
namespace UsvLink {
class Command;
struct CommandDefaultTypeInternal;
extern CommandDefaultTypeInternal _Command_default_instance_;
}  // namespace UsvLink
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace UsvLink {

// ===================================================================


// -------------------------------------------------------------------

class Command final :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:UsvLink.Command) */ {
 public:
  inline Command() : Command(nullptr) {}
  ~Command() override;
  template<typename = void>
  explicit PROTOBUF_CONSTEXPR Command(::google::protobuf::internal::ConstantInitialized);

  inline Command(const Command& from)
      : Command(nullptr, from) {}
  Command(Command&& from) noexcept
    : Command() {
    *this = ::std::move(from);
  }

  inline Command& operator=(const Command& from) {
    CopyFrom(from);
    return *this;
  }
  inline Command& operator=(Command&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Command& default_instance() {
    return *internal_default_instance();
  }
  static inline const Command* internal_default_instance() {
    return reinterpret_cast<const Command*>(
               &_Command_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(Command& a, Command& b) {
    a.Swap(&b);
  }
  inline void Swap(Command* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr &&
        GetArena() == other->GetArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Command* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Command* New(::google::protobuf::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Command>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const Command& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom( const Command& from) {
    Command::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::google::protobuf::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target, ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  ::google::protobuf::internal::CachedSize* AccessCachedSize() const final;
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(Command* other);

  private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() {
    return "UsvLink.Command";
  }
  protected:
  explicit Command(::google::protobuf::Arena* arena);
  Command(::google::protobuf::Arena* arena, const Command& from);
  public:

  static const ClassData _class_data_;
  const ::google::protobuf::Message::ClassData*GetClassData() const final;

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kCmdIdFieldNumber = 1,
    kParam1FieldNumber = 2,
    kParam2FieldNumber = 3,
    kParam3FieldNumber = 4,
    kParam4FieldNumber = 5,
    kParam5FieldNumber = 6,
    kParam6FieldNumber = 7,
    kParam7FieldNumber = 8,
  };
  // .UsvLink.CmdId cmd_id = 1;
  void clear_cmd_id() ;
  ::UsvLink::CmdId cmd_id() const;
  void set_cmd_id(::UsvLink::CmdId value);

  private:
  ::UsvLink::CmdId _internal_cmd_id() const;
  void _internal_set_cmd_id(::UsvLink::CmdId value);

  public:
  // float param1 = 2;
  void clear_param1() ;
  float param1() const;
  void set_param1(float value);

  private:
  float _internal_param1() const;
  void _internal_set_param1(float value);

  public:
  // float param2 = 3;
  void clear_param2() ;
  float param2() const;
  void set_param2(float value);

  private:
  float _internal_param2() const;
  void _internal_set_param2(float value);

  public:
  // float param3 = 4;
  void clear_param3() ;
  float param3() const;
  void set_param3(float value);

  private:
  float _internal_param3() const;
  void _internal_set_param3(float value);

  public:
  // float param4 = 5;
  void clear_param4() ;
  float param4() const;
  void set_param4(float value);

  private:
  float _internal_param4() const;
  void _internal_set_param4(float value);

  public:
  // float param5 = 6;
  void clear_param5() ;
  float param5() const;
  void set_param5(float value);

  private:
  float _internal_param5() const;
  void _internal_set_param5(float value);

  public:
  // float param6 = 7;
  void clear_param6() ;
  float param6() const;
  void set_param6(float value);

  private:
  float _internal_param6() const;
  void _internal_set_param6(float value);

  public:
  // float param7 = 8;
  void clear_param7() ;
  float param7() const;
  void set_param7(float value);

  private:
  float _internal_param7() const;
  void _internal_set_param7(float value);

  public:
  // @@protoc_insertion_point(class_scope:UsvLink.Command)
 private:
  class _Internal;

  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      3, 8, 0,
      0, 2>
      _table_;
  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {

        inline explicit constexpr Impl_(
            ::google::protobuf::internal::ConstantInitialized) noexcept;
        inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                              ::google::protobuf::Arena* arena);
        inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                              ::google::protobuf::Arena* arena, const Impl_& from);
    int cmd_id_;
    float param1_;
    float param2_;
    float param3_;
    float param4_;
    float param5_;
    float param6_;
    float param7_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_msg_5fcommand_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// Command

// .UsvLink.CmdId cmd_id = 1;
inline void Command::clear_cmd_id() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.cmd_id_ = 0;
}
inline ::UsvLink::CmdId Command::cmd_id() const {
  // @@protoc_insertion_point(field_get:UsvLink.Command.cmd_id)
  return _internal_cmd_id();
}
inline void Command::set_cmd_id(::UsvLink::CmdId value) {
  _internal_set_cmd_id(value);
  // @@protoc_insertion_point(field_set:UsvLink.Command.cmd_id)
}
inline ::UsvLink::CmdId Command::_internal_cmd_id() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return static_cast<::UsvLink::CmdId>(_impl_.cmd_id_);
}
inline void Command::_internal_set_cmd_id(::UsvLink::CmdId value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.cmd_id_ = value;
}

// float param1 = 2;
inline void Command::clear_param1() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.param1_ = 0;
}
inline float Command::param1() const {
  // @@protoc_insertion_point(field_get:UsvLink.Command.param1)
  return _internal_param1();
}
inline void Command::set_param1(float value) {
  _internal_set_param1(value);
  // @@protoc_insertion_point(field_set:UsvLink.Command.param1)
}
inline float Command::_internal_param1() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.param1_;
}
inline void Command::_internal_set_param1(float value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.param1_ = value;
}

// float param2 = 3;
inline void Command::clear_param2() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.param2_ = 0;
}
inline float Command::param2() const {
  // @@protoc_insertion_point(field_get:UsvLink.Command.param2)
  return _internal_param2();
}
inline void Command::set_param2(float value) {
  _internal_set_param2(value);
  // @@protoc_insertion_point(field_set:UsvLink.Command.param2)
}
inline float Command::_internal_param2() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.param2_;
}
inline void Command::_internal_set_param2(float value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.param2_ = value;
}

// float param3 = 4;
inline void Command::clear_param3() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.param3_ = 0;
}
inline float Command::param3() const {
  // @@protoc_insertion_point(field_get:UsvLink.Command.param3)
  return _internal_param3();
}
inline void Command::set_param3(float value) {
  _internal_set_param3(value);
  // @@protoc_insertion_point(field_set:UsvLink.Command.param3)
}
inline float Command::_internal_param3() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.param3_;
}
inline void Command::_internal_set_param3(float value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.param3_ = value;
}

// float param4 = 5;
inline void Command::clear_param4() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.param4_ = 0;
}
inline float Command::param4() const {
  // @@protoc_insertion_point(field_get:UsvLink.Command.param4)
  return _internal_param4();
}
inline void Command::set_param4(float value) {
  _internal_set_param4(value);
  // @@protoc_insertion_point(field_set:UsvLink.Command.param4)
}
inline float Command::_internal_param4() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.param4_;
}
inline void Command::_internal_set_param4(float value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.param4_ = value;
}

// float param5 = 6;
inline void Command::clear_param5() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.param5_ = 0;
}
inline float Command::param5() const {
  // @@protoc_insertion_point(field_get:UsvLink.Command.param5)
  return _internal_param5();
}
inline void Command::set_param5(float value) {
  _internal_set_param5(value);
  // @@protoc_insertion_point(field_set:UsvLink.Command.param5)
}
inline float Command::_internal_param5() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.param5_;
}
inline void Command::_internal_set_param5(float value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.param5_ = value;
}

// float param6 = 7;
inline void Command::clear_param6() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.param6_ = 0;
}
inline float Command::param6() const {
  // @@protoc_insertion_point(field_get:UsvLink.Command.param6)
  return _internal_param6();
}
inline void Command::set_param6(float value) {
  _internal_set_param6(value);
  // @@protoc_insertion_point(field_set:UsvLink.Command.param6)
}
inline float Command::_internal_param6() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.param6_;
}
inline void Command::_internal_set_param6(float value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.param6_ = value;
}

// float param7 = 8;
inline void Command::clear_param7() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.param7_ = 0;
}
inline float Command::param7() const {
  // @@protoc_insertion_point(field_get:UsvLink.Command.param7)
  return _internal_param7();
}
inline void Command::set_param7(float value) {
  _internal_set_param7(value);
  // @@protoc_insertion_point(field_set:UsvLink.Command.param7)
}
inline float Command::_internal_param7() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.param7_;
}
inline void Command::_internal_set_param7(float value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.param7_ = value;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace UsvLink


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // GOOGLE_PROTOBUF_INCLUDED_msg_5fcommand_2eproto_2epb_2eh
