// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: msg_param_write_response.proto

#include "msg_param_write_response.pb.h"

#include <algorithm>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
#include "google/protobuf/generated_message_tctable_impl.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace UsvLink {

inline constexpr ParamWriteResponse::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        err_msg_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        ack_{0} {}

template <typename>
PROTOBUF_CONSTEXPR ParamWriteResponse::ParamWriteResponse(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct ParamWriteResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ParamWriteResponseDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~ParamWriteResponseDefaultTypeInternal() {}
  union {
    ParamWriteResponse _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ParamWriteResponseDefaultTypeInternal _ParamWriteResponse_default_instance_;
}  // namespace UsvLink
static ::_pb::Metadata file_level_metadata_msg_5fparam_5fwrite_5fresponse_2eproto[1];
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_msg_5fparam_5fwrite_5fresponse_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_msg_5fparam_5fwrite_5fresponse_2eproto = nullptr;
const ::uint32_t TableStruct_msg_5fparam_5fwrite_5fresponse_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(
    protodesc_cold) = {
    PROTOBUF_FIELD_OFFSET(::UsvLink::ParamWriteResponse, _impl_._has_bits_),
    PROTOBUF_FIELD_OFFSET(::UsvLink::ParamWriteResponse, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::UsvLink::ParamWriteResponse, _impl_.ack_),
    PROTOBUF_FIELD_OFFSET(::UsvLink::ParamWriteResponse, _impl_.err_msg_),
    ~0u,
    0,
};

static const ::_pbi::MigrationSchema
    schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
        {0, 10, -1, sizeof(::UsvLink::ParamWriteResponse)},
};

static const ::_pb::Message* const file_default_instances[] = {
    &::UsvLink::_ParamWriteResponse_default_instance_._instance,
};
const char descriptor_table_protodef_msg_5fparam_5fwrite_5fresponse_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
    "\n\036msg_param_write_response.proto\022\007UsvLin"
    "k\"C\n\022ParamWriteResponse\022\013\n\003ack\030\001 \001(\005\022\024\n\007"
    "err_msg\030\002 \001(\tH\000\210\001\001B\n\n\010_err_msgb\006proto3"
};
static ::absl::once_flag descriptor_table_msg_5fparam_5fwrite_5fresponse_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_msg_5fparam_5fwrite_5fresponse_2eproto = {
    false,
    false,
    118,
    descriptor_table_protodef_msg_5fparam_5fwrite_5fresponse_2eproto,
    "msg_param_write_response.proto",
    &descriptor_table_msg_5fparam_5fwrite_5fresponse_2eproto_once,
    nullptr,
    0,
    1,
    schemas,
    file_default_instances,
    TableStruct_msg_5fparam_5fwrite_5fresponse_2eproto::offsets,
    file_level_metadata_msg_5fparam_5fwrite_5fresponse_2eproto,
    file_level_enum_descriptors_msg_5fparam_5fwrite_5fresponse_2eproto,
    file_level_service_descriptors_msg_5fparam_5fwrite_5fresponse_2eproto,
};

// This function exists to be marked as weak.
// It can significantly speed up compilation by breaking up LLVM's SCC
// in the .pb.cc translation units. Large translation units see a
// reduction of more than 35% of walltime for optimized builds. Without
// the weak attribute all the messages in the file, including all the
// vtables and everything they use become part of the same SCC through
// a cycle like:
// GetMetadata -> descriptor table -> default instances ->
//   vtables -> GetMetadata
// By adding a weak function here we break the connection from the
// individual vtables back into the descriptor table.
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_msg_5fparam_5fwrite_5fresponse_2eproto_getter() {
  return &descriptor_table_msg_5fparam_5fwrite_5fresponse_2eproto;
}
// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2
static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_msg_5fparam_5fwrite_5fresponse_2eproto(&descriptor_table_msg_5fparam_5fwrite_5fresponse_2eproto);
namespace UsvLink {
// ===================================================================

class ParamWriteResponse::_Internal {
 public:
  using HasBits = decltype(std::declval<ParamWriteResponse>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
    8 * PROTOBUF_FIELD_OFFSET(ParamWriteResponse, _impl_._has_bits_);
  static void set_has_err_msg(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
};

ParamWriteResponse::ParamWriteResponse(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:UsvLink.ParamWriteResponse)
}
inline PROTOBUF_NDEBUG_INLINE ParamWriteResponse::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        err_msg_(arena, from.err_msg_) {}

ParamWriteResponse::ParamWriteResponse(
    ::google::protobuf::Arena* arena,
    const ParamWriteResponse& from)
    : ::google::protobuf::Message(arena) {
  ParamWriteResponse* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);
  _impl_.ack_ = from._impl_.ack_;

  // @@protoc_insertion_point(copy_constructor:UsvLink.ParamWriteResponse)
}
inline PROTOBUF_NDEBUG_INLINE ParamWriteResponse::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0},
        err_msg_(arena) {}

inline void ParamWriteResponse::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.ack_ = {};
}
ParamWriteResponse::~ParamWriteResponse() {
  // @@protoc_insertion_point(destructor:UsvLink.ParamWriteResponse)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void ParamWriteResponse::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.err_msg_.Destroy();
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void ParamWriteResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:UsvLink.ParamWriteResponse)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    _impl_.err_msg_.ClearNonDefaultToEmpty();
  }
  _impl_.ack_ = 0;
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* ParamWriteResponse::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 42, 2> ParamWriteResponse::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(ParamWriteResponse, _impl_._has_bits_),
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_ParamWriteResponse_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    // optional string err_msg = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 0, 0, PROTOBUF_FIELD_OFFSET(ParamWriteResponse, _impl_.err_msg_)}},
    // int32 ack = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(ParamWriteResponse, _impl_.ack_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(ParamWriteResponse, _impl_.ack_)}},
  }}, {{
    65535, 65535
  }}, {{
    // int32 ack = 1;
    {PROTOBUF_FIELD_OFFSET(ParamWriteResponse, _impl_.ack_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
    // optional string err_msg = 2;
    {PROTOBUF_FIELD_OFFSET(ParamWriteResponse, _impl_.err_msg_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\32\0\7\0\0\0\0\0"
    "UsvLink.ParamWriteResponse"
    "err_msg"
  }},
};

::uint8_t* ParamWriteResponse::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:UsvLink.ParamWriteResponse)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // int32 ack = 1;
  if (this->_internal_ack() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt32ToArrayWithField<1>(
            stream, this->_internal_ack(), target);
  }

  cached_has_bits = _impl_._has_bits_[0];
  // optional string err_msg = 2;
  if (cached_has_bits & 0x00000001u) {
    const std::string& _s = this->_internal_err_msg();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "UsvLink.ParamWriteResponse.err_msg");
    target = stream->WriteStringMaybeAliased(2, _s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:UsvLink.ParamWriteResponse)
  return target;
}

::size_t ParamWriteResponse::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:UsvLink.ParamWriteResponse)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // optional string err_msg = 2;
  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_err_msg());
  }

  // int32 ack = 1;
  if (this->_internal_ack() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
        this->_internal_ack());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData ParamWriteResponse::_class_data_ = {
    ParamWriteResponse::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* ParamWriteResponse::GetClassData() const {
  return &_class_data_;
}

void ParamWriteResponse::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<ParamWriteResponse*>(&to_msg);
  auto& from = static_cast<const ParamWriteResponse&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:UsvLink.ParamWriteResponse)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if ((from._impl_._has_bits_[0] & 0x00000001u) != 0) {
    _this->_internal_set_err_msg(from._internal_err_msg());
  }
  if (from._internal_ack() != 0) {
    _this->_internal_set_ack(from._internal_ack());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void ParamWriteResponse::CopyFrom(const ParamWriteResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:UsvLink.ParamWriteResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool ParamWriteResponse::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* ParamWriteResponse::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void ParamWriteResponse::InternalSwap(ParamWriteResponse* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.err_msg_, &other->_impl_.err_msg_, arena);
        swap(_impl_.ack_, other->_impl_.ack_);
}

::google::protobuf::Metadata ParamWriteResponse::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_msg_5fparam_5fwrite_5fresponse_2eproto_getter, &descriptor_table_msg_5fparam_5fwrite_5fresponse_2eproto_once,
      file_level_metadata_msg_5fparam_5fwrite_5fresponse_2eproto[0]);
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace UsvLink
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
#include "google/protobuf/port_undef.inc"
