// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: msg_mission_set_current.proto
// Protobuf C++ Version: 4.25.1

#ifndef GOOGLE_PROTOBUF_INCLUDED_msg_5fmission_5fset_5fcurrent_2eproto_2epb_2eh
#define GOOGLE_PROTOBUF_INCLUDED_msg_5fmission_5fset_5fcurrent_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/port_def.inc"
#if PROTOBUF_VERSION < 4025000
#error "This file was generated by a newer version of protoc which is"
#error "incompatible with your Protocol Buffer headers. Please update"
#error "your headers."
#endif  // PROTOBUF_VERSION

#if 4025001 < PROTOBUF_MIN_PROTOC_VERSION
#error "This file was generated by an older version of protoc which is"
#error "incompatible with your Protocol Buffer headers. Please"
#error "regenerate this file with a newer version of protoc."
#endif  // PROTOBUF_MIN_PROTOC_VERSION
#include "google/protobuf/port_undef.inc"
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_msg_5fmission_5fset_5fcurrent_2eproto

namespace google {
namespace protobuf {
namespace internal {
class AnyMetadata;
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_msg_5fmission_5fset_5fcurrent_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_msg_5fmission_5fset_5fcurrent_2eproto;
namespace UsvLink {
class MissionSetCurrent;
struct MissionSetCurrentDefaultTypeInternal;
extern MissionSetCurrentDefaultTypeInternal _MissionSetCurrent_default_instance_;
}  // namespace UsvLink
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace UsvLink {

// ===================================================================


// -------------------------------------------------------------------

class MissionSetCurrent final :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:UsvLink.MissionSetCurrent) */ {
 public:
  inline MissionSetCurrent() : MissionSetCurrent(nullptr) {}
  ~MissionSetCurrent() override;
  template<typename = void>
  explicit PROTOBUF_CONSTEXPR MissionSetCurrent(::google::protobuf::internal::ConstantInitialized);

  inline MissionSetCurrent(const MissionSetCurrent& from)
      : MissionSetCurrent(nullptr, from) {}
  MissionSetCurrent(MissionSetCurrent&& from) noexcept
    : MissionSetCurrent() {
    *this = ::std::move(from);
  }

  inline MissionSetCurrent& operator=(const MissionSetCurrent& from) {
    CopyFrom(from);
    return *this;
  }
  inline MissionSetCurrent& operator=(MissionSetCurrent&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const MissionSetCurrent& default_instance() {
    return *internal_default_instance();
  }
  static inline const MissionSetCurrent* internal_default_instance() {
    return reinterpret_cast<const MissionSetCurrent*>(
               &_MissionSetCurrent_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(MissionSetCurrent& a, MissionSetCurrent& b) {
    a.Swap(&b);
  }
  inline void Swap(MissionSetCurrent* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr &&
        GetArena() == other->GetArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(MissionSetCurrent* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  MissionSetCurrent* New(::google::protobuf::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<MissionSetCurrent>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const MissionSetCurrent& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom( const MissionSetCurrent& from) {
    MissionSetCurrent::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::google::protobuf::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target, ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  ::google::protobuf::internal::CachedSize* AccessCachedSize() const final;
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(MissionSetCurrent* other);

  private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() {
    return "UsvLink.MissionSetCurrent";
  }
  protected:
  explicit MissionSetCurrent(::google::protobuf::Arena* arena);
  MissionSetCurrent(::google::protobuf::Arena* arena, const MissionSetCurrent& from);
  public:

  static const ClassData _class_data_;
  const ::google::protobuf::Message::ClassData*GetClassData() const final;

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kSeqFieldNumber = 1,
    kResetFieldNumber = 2,
  };
  // int32 seq = 1;
  void clear_seq() ;
  ::int32_t seq() const;
  void set_seq(::int32_t value);

  private:
  ::int32_t _internal_seq() const;
  void _internal_set_seq(::int32_t value);

  public:
  // bool reset = 2;
  void clear_reset() ;
  bool reset() const;
  void set_reset(bool value);

  private:
  bool _internal_reset() const;
  void _internal_set_reset(bool value);

  public:
  // @@protoc_insertion_point(class_scope:UsvLink.MissionSetCurrent)
 private:
  class _Internal;

  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      1, 2, 0,
      0, 2>
      _table_;
  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {

        inline explicit constexpr Impl_(
            ::google::protobuf::internal::ConstantInitialized) noexcept;
        inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                              ::google::protobuf::Arena* arena);
        inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                              ::google::protobuf::Arena* arena, const Impl_& from);
    ::int32_t seq_;
    bool reset_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_msg_5fmission_5fset_5fcurrent_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// MissionSetCurrent

// int32 seq = 1;
inline void MissionSetCurrent::clear_seq() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.seq_ = 0;
}
inline ::int32_t MissionSetCurrent::seq() const {
  // @@protoc_insertion_point(field_get:UsvLink.MissionSetCurrent.seq)
  return _internal_seq();
}
inline void MissionSetCurrent::set_seq(::int32_t value) {
  _internal_set_seq(value);
  // @@protoc_insertion_point(field_set:UsvLink.MissionSetCurrent.seq)
}
inline ::int32_t MissionSetCurrent::_internal_seq() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.seq_;
}
inline void MissionSetCurrent::_internal_set_seq(::int32_t value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.seq_ = value;
}

// bool reset = 2;
inline void MissionSetCurrent::clear_reset() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.reset_ = false;
}
inline bool MissionSetCurrent::reset() const {
  // @@protoc_insertion_point(field_get:UsvLink.MissionSetCurrent.reset)
  return _internal_reset();
}
inline void MissionSetCurrent::set_reset(bool value) {
  _internal_set_reset(value);
  // @@protoc_insertion_point(field_set:UsvLink.MissionSetCurrent.reset)
}
inline bool MissionSetCurrent::_internal_reset() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.reset_;
}
inline void MissionSetCurrent::_internal_set_reset(bool value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.reset_ = value;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace UsvLink


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // GOOGLE_PROTOBUF_INCLUDED_msg_5fmission_5fset_5fcurrent_2eproto_2epb_2eh
