// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: msg_mission_current.proto
// Protobuf C++ Version: 4.25.1

#ifndef GOOGLE_PROTOBUF_INCLUDED_msg_5fmission_5fcurrent_2eproto_2epb_2eh
#define GOOGLE_PROTOBUF_INCLUDED_msg_5fmission_5fcurrent_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/port_def.inc"
#if PROTOBUF_VERSION < 4025000
#error "This file was generated by a newer version of protoc which is"
#error "incompatible with your Protocol Buffer headers. Please update"
#error "your headers."
#endif  // PROTOBUF_VERSION

#if 4025001 < PROTOBUF_MIN_PROTOC_VERSION
#error "This file was generated by an older version of protoc which is"
#error "incompatible with your Protocol Buffer headers. Please"
#error "regenerate this file with a newer version of protoc."
#endif  // PROTOBUF_MIN_PROTOC_VERSION
#include "google/protobuf/port_undef.inc"
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
#include "msg_enum.pb.h"
#include "msg_mission_item.pb.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_msg_5fmission_5fcurrent_2eproto

namespace google {
namespace protobuf {
namespace internal {
class AnyMetadata;
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_msg_5fmission_5fcurrent_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_msg_5fmission_5fcurrent_2eproto;
namespace UsvLink {
class MissionCurrent;
struct MissionCurrentDefaultTypeInternal;
extern MissionCurrentDefaultTypeInternal _MissionCurrent_default_instance_;
}  // namespace UsvLink
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace UsvLink {

// ===================================================================


// -------------------------------------------------------------------

class MissionCurrent final :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:UsvLink.MissionCurrent) */ {
 public:
  inline MissionCurrent() : MissionCurrent(nullptr) {}
  ~MissionCurrent() override;
  template<typename = void>
  explicit PROTOBUF_CONSTEXPR MissionCurrent(::google::protobuf::internal::ConstantInitialized);

  inline MissionCurrent(const MissionCurrent& from)
      : MissionCurrent(nullptr, from) {}
  MissionCurrent(MissionCurrent&& from) noexcept
    : MissionCurrent() {
    *this = ::std::move(from);
  }

  inline MissionCurrent& operator=(const MissionCurrent& from) {
    CopyFrom(from);
    return *this;
  }
  inline MissionCurrent& operator=(MissionCurrent&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const MissionCurrent& default_instance() {
    return *internal_default_instance();
  }
  static inline const MissionCurrent* internal_default_instance() {
    return reinterpret_cast<const MissionCurrent*>(
               &_MissionCurrent_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(MissionCurrent& a, MissionCurrent& b) {
    a.Swap(&b);
  }
  inline void Swap(MissionCurrent* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr &&
        GetArena() == other->GetArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(MissionCurrent* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  MissionCurrent* New(::google::protobuf::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<MissionCurrent>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const MissionCurrent& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom( const MissionCurrent& from) {
    MissionCurrent::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::google::protobuf::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target, ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  ::google::protobuf::internal::CachedSize* AccessCachedSize() const final;
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(MissionCurrent* other);

  private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() {
    return "UsvLink.MissionCurrent";
  }
  protected:
  explicit MissionCurrent(::google::protobuf::Arena* arena);
  MissionCurrent(::google::protobuf::Arena* arena, const MissionCurrent& from);
  public:

  static const ClassData _class_data_;
  const ::google::protobuf::Message::ClassData*GetClassData() const final;

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kMissionItemFieldNumber = 3,
    kMissionStateFieldNumber = 1,
    kMissionIdFieldNumber = 2,
  };
  // .UsvLink.MissionItem mission_item = 3;
  bool has_mission_item() const;
  void clear_mission_item() ;
  const ::UsvLink::MissionItem& mission_item() const;
  PROTOBUF_NODISCARD ::UsvLink::MissionItem* release_mission_item();
  ::UsvLink::MissionItem* mutable_mission_item();
  void set_allocated_mission_item(::UsvLink::MissionItem* value);
  void unsafe_arena_set_allocated_mission_item(::UsvLink::MissionItem* value);
  ::UsvLink::MissionItem* unsafe_arena_release_mission_item();

  private:
  const ::UsvLink::MissionItem& _internal_mission_item() const;
  ::UsvLink::MissionItem* _internal_mutable_mission_item();

  public:
  // .UsvLink.MissionState mission_state = 1;
  void clear_mission_state() ;
  ::UsvLink::MissionState mission_state() const;
  void set_mission_state(::UsvLink::MissionState value);

  private:
  ::UsvLink::MissionState _internal_mission_state() const;
  void _internal_set_mission_state(::UsvLink::MissionState value);

  public:
  // int32 mission_id = 2;
  void clear_mission_id() ;
  ::int32_t mission_id() const;
  void set_mission_id(::int32_t value);

  private:
  ::int32_t _internal_mission_id() const;
  void _internal_set_mission_id(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:UsvLink.MissionCurrent)
 private:
  class _Internal;

  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      2, 3, 1,
      0, 2>
      _table_;
  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {

        inline explicit constexpr Impl_(
            ::google::protobuf::internal::ConstantInitialized) noexcept;
        inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                              ::google::protobuf::Arena* arena);
        inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                              ::google::protobuf::Arena* arena, const Impl_& from);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    ::UsvLink::MissionItem* mission_item_;
    int mission_state_;
    ::int32_t mission_id_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_msg_5fmission_5fcurrent_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// MissionCurrent

// .UsvLink.MissionState mission_state = 1;
inline void MissionCurrent::clear_mission_state() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.mission_state_ = 0;
}
inline ::UsvLink::MissionState MissionCurrent::mission_state() const {
  // @@protoc_insertion_point(field_get:UsvLink.MissionCurrent.mission_state)
  return _internal_mission_state();
}
inline void MissionCurrent::set_mission_state(::UsvLink::MissionState value) {
  _internal_set_mission_state(value);
  // @@protoc_insertion_point(field_set:UsvLink.MissionCurrent.mission_state)
}
inline ::UsvLink::MissionState MissionCurrent::_internal_mission_state() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return static_cast<::UsvLink::MissionState>(_impl_.mission_state_);
}
inline void MissionCurrent::_internal_set_mission_state(::UsvLink::MissionState value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.mission_state_ = value;
}

// int32 mission_id = 2;
inline void MissionCurrent::clear_mission_id() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.mission_id_ = 0;
}
inline ::int32_t MissionCurrent::mission_id() const {
  // @@protoc_insertion_point(field_get:UsvLink.MissionCurrent.mission_id)
  return _internal_mission_id();
}
inline void MissionCurrent::set_mission_id(::int32_t value) {
  _internal_set_mission_id(value);
  // @@protoc_insertion_point(field_set:UsvLink.MissionCurrent.mission_id)
}
inline ::int32_t MissionCurrent::_internal_mission_id() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.mission_id_;
}
inline void MissionCurrent::_internal_set_mission_id(::int32_t value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.mission_id_ = value;
}

// .UsvLink.MissionItem mission_item = 3;
inline bool MissionCurrent::has_mission_item() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.mission_item_ != nullptr);
  return value;
}
inline const ::UsvLink::MissionItem& MissionCurrent::_internal_mission_item() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  const ::UsvLink::MissionItem* p = _impl_.mission_item_;
  return p != nullptr ? *p : reinterpret_cast<const ::UsvLink::MissionItem&>(::UsvLink::_MissionItem_default_instance_);
}
inline const ::UsvLink::MissionItem& MissionCurrent::mission_item() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:UsvLink.MissionCurrent.mission_item)
  return _internal_mission_item();
}
inline void MissionCurrent::unsafe_arena_set_allocated_mission_item(::UsvLink::MissionItem* value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.mission_item_);
  }
  _impl_.mission_item_ = reinterpret_cast<::UsvLink::MissionItem*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:UsvLink.MissionCurrent.mission_item)
}
inline ::UsvLink::MissionItem* MissionCurrent::release_mission_item() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::UsvLink::MissionItem* released = _impl_.mission_item_;
  _impl_.mission_item_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
  released = ::google::protobuf::internal::DuplicateIfNonNull(released);
  if (GetArena() == nullptr) {
    delete old;
  }
#else   // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArena() != nullptr) {
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return released;
}
inline ::UsvLink::MissionItem* MissionCurrent::unsafe_arena_release_mission_item() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  // @@protoc_insertion_point(field_release:UsvLink.MissionCurrent.mission_item)

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::UsvLink::MissionItem* temp = _impl_.mission_item_;
  _impl_.mission_item_ = nullptr;
  return temp;
}
inline ::UsvLink::MissionItem* MissionCurrent::_internal_mutable_mission_item() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_._has_bits_[0] |= 0x00000001u;
  if (_impl_.mission_item_ == nullptr) {
    auto* p = CreateMaybeMessage<::UsvLink::MissionItem>(GetArena());
    _impl_.mission_item_ = reinterpret_cast<::UsvLink::MissionItem*>(p);
  }
  return _impl_.mission_item_;
}
inline ::UsvLink::MissionItem* MissionCurrent::mutable_mission_item() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::UsvLink::MissionItem* _msg = _internal_mutable_mission_item();
  // @@protoc_insertion_point(field_mutable:UsvLink.MissionCurrent.mission_item)
  return _msg;
}
inline void MissionCurrent::set_allocated_mission_item(::UsvLink::MissionItem* value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.mission_item_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::MessageLite*>(value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }

  _impl_.mission_item_ = reinterpret_cast<::UsvLink::MissionItem*>(value);
  // @@protoc_insertion_point(field_set_allocated:UsvLink.MissionCurrent.mission_item)
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace UsvLink


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // GOOGLE_PROTOBUF_INCLUDED_msg_5fmission_5fcurrent_2eproto_2epb_2eh
