// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: msg_param_item.proto
// Protobuf C++ Version: 4.25.1

#ifndef GOOGLE_PROTOBUF_INCLUDED_msg_5fparam_5fitem_2eproto_2epb_2eh
#define GOOGLE_PROTOBUF_INCLUDED_msg_5fparam_5fitem_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/port_def.inc"
#if PROTOBUF_VERSION < 4025000
#error "This file was generated by a newer version of protoc which is"
#error "incompatible with your Protocol Buffer headers. Please update"
#error "your headers."
#endif  // PROTOBUF_VERSION

#if 4025001 < PROTOBUF_MIN_PROTOC_VERSION
#error "This file was generated by an older version of protoc which is"
#error "incompatible with your Protocol Buffer headers. Please"
#error "regenerate this file with a newer version of protoc."
#endif  // PROTOBUF_MIN_PROTOC_VERSION
#include "google/protobuf/port_undef.inc"
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_msg_5fparam_5fitem_2eproto

namespace google {
namespace protobuf {
namespace internal {
class AnyMetadata;
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_msg_5fparam_5fitem_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_msg_5fparam_5fitem_2eproto;
namespace UsvLink {
class ParamItem;
struct ParamItemDefaultTypeInternal;
extern ParamItemDefaultTypeInternal _ParamItem_default_instance_;
}  // namespace UsvLink
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace UsvLink {

// ===================================================================


// -------------------------------------------------------------------

class ParamItem final :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:UsvLink.ParamItem) */ {
 public:
  inline ParamItem() : ParamItem(nullptr) {}
  ~ParamItem() override;
  template<typename = void>
  explicit PROTOBUF_CONSTEXPR ParamItem(::google::protobuf::internal::ConstantInitialized);

  inline ParamItem(const ParamItem& from)
      : ParamItem(nullptr, from) {}
  ParamItem(ParamItem&& from) noexcept
    : ParamItem() {
    *this = ::std::move(from);
  }

  inline ParamItem& operator=(const ParamItem& from) {
    CopyFrom(from);
    return *this;
  }
  inline ParamItem& operator=(ParamItem&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ParamItem& default_instance() {
    return *internal_default_instance();
  }
  static inline const ParamItem* internal_default_instance() {
    return reinterpret_cast<const ParamItem*>(
               &_ParamItem_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(ParamItem& a, ParamItem& b) {
    a.Swap(&b);
  }
  inline void Swap(ParamItem* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr &&
        GetArena() == other->GetArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ParamItem* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ParamItem* New(::google::protobuf::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<ParamItem>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const ParamItem& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom( const ParamItem& from) {
    ParamItem::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::google::protobuf::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target, ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  ::google::protobuf::internal::CachedSize* AccessCachedSize() const final;
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(ParamItem* other);

  private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() {
    return "UsvLink.ParamItem";
  }
  protected:
  explicit ParamItem(::google::protobuf::Arena* arena);
  ParamItem(::google::protobuf::Arena* arena, const ParamItem& from);
  public:

  static const ClassData _class_data_;
  const ::google::protobuf::Message::ClassData*GetClassData() const final;

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kParamIdFieldNumber = 1,
    kParamValueFieldNumber = 2,
    kParamIndexFieldNumber = 3,
  };
  // string param_id = 1;
  void clear_param_id() ;
  const std::string& param_id() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_param_id(Arg_&& arg, Args_... args);
  std::string* mutable_param_id();
  PROTOBUF_NODISCARD std::string* release_param_id();
  void set_allocated_param_id(std::string* value);

  private:
  const std::string& _internal_param_id() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_param_id(
      const std::string& value);
  std::string* _internal_mutable_param_id();

  public:
  // float param_value = 2;
  void clear_param_value() ;
  float param_value() const;
  void set_param_value(float value);

  private:
  float _internal_param_value() const;
  void _internal_set_param_value(float value);

  public:
  // int32 param_index = 3;
  void clear_param_index() ;
  ::int32_t param_index() const;
  void set_param_index(::int32_t value);

  private:
  ::int32_t _internal_param_index() const;
  void _internal_set_param_index(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:UsvLink.ParamItem)
 private:
  class _Internal;

  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      2, 3, 0,
      34, 2>
      _table_;
  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {

        inline explicit constexpr Impl_(
            ::google::protobuf::internal::ConstantInitialized) noexcept;
        inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                              ::google::protobuf::Arena* arena);
        inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                              ::google::protobuf::Arena* arena, const Impl_& from);
    ::google::protobuf::internal::ArenaStringPtr param_id_;
    float param_value_;
    ::int32_t param_index_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_msg_5fparam_5fitem_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// ParamItem

// string param_id = 1;
inline void ParamItem::clear_param_id() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.param_id_.ClearToEmpty();
}
inline const std::string& ParamItem::param_id() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:UsvLink.ParamItem.param_id)
  return _internal_param_id();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void ParamItem::set_param_id(Arg_&& arg,
                                                     Args_... args) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.param_id_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:UsvLink.ParamItem.param_id)
}
inline std::string* ParamItem::mutable_param_id() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_param_id();
  // @@protoc_insertion_point(field_mutable:UsvLink.ParamItem.param_id)
  return _s;
}
inline const std::string& ParamItem::_internal_param_id() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.param_id_.Get();
}
inline void ParamItem::_internal_set_param_id(const std::string& value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.param_id_.Set(value, GetArena());
}
inline std::string* ParamItem::_internal_mutable_param_id() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  return _impl_.param_id_.Mutable( GetArena());
}
inline std::string* ParamItem::release_param_id() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  // @@protoc_insertion_point(field_release:UsvLink.ParamItem.param_id)
  return _impl_.param_id_.Release();
}
inline void ParamItem::set_allocated_param_id(std::string* value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.param_id_.SetAllocated(value, GetArena());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.param_id_.IsDefault()) {
          _impl_.param_id_.Set("", GetArena());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:UsvLink.ParamItem.param_id)
}

// float param_value = 2;
inline void ParamItem::clear_param_value() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.param_value_ = 0;
}
inline float ParamItem::param_value() const {
  // @@protoc_insertion_point(field_get:UsvLink.ParamItem.param_value)
  return _internal_param_value();
}
inline void ParamItem::set_param_value(float value) {
  _internal_set_param_value(value);
  // @@protoc_insertion_point(field_set:UsvLink.ParamItem.param_value)
}
inline float ParamItem::_internal_param_value() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.param_value_;
}
inline void ParamItem::_internal_set_param_value(float value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.param_value_ = value;
}

// int32 param_index = 3;
inline void ParamItem::clear_param_index() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.param_index_ = 0;
}
inline ::int32_t ParamItem::param_index() const {
  // @@protoc_insertion_point(field_get:UsvLink.ParamItem.param_index)
  return _internal_param_index();
}
inline void ParamItem::set_param_index(::int32_t value) {
  _internal_set_param_index(value);
  // @@protoc_insertion_point(field_set:UsvLink.ParamItem.param_index)
}
inline ::int32_t ParamItem::_internal_param_index() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.param_index_;
}
inline void ParamItem::_internal_set_param_index(::int32_t value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.param_index_ = value;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace UsvLink


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // GOOGLE_PROTOBUF_INCLUDED_msg_5fparam_5fitem_2eproto_2epb_2eh
