// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: msg_enum.proto

#include "msg_enum.pb.h"

#include <algorithm>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
#include "google/protobuf/generated_message_tctable_impl.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace UsvLink {
}  // namespace UsvLink
static const ::_pb::EnumDescriptor* file_level_enum_descriptors_msg_5fenum_2eproto[6];
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_msg_5fenum_2eproto = nullptr;
const ::uint32_t TableStruct_msg_5fenum_2eproto::offsets[1] = {};
static constexpr ::_pbi::MigrationSchema* schemas = nullptr;
static constexpr ::_pb::Message* const* file_default_instances = nullptr;
const char descriptor_table_protodef_msg_5fenum_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
    "\n\016msg_enum.proto\022\007UsvLink*>\n\006MsgSrc\022\017\n\013M"
    "SG_SRC_USV\020\000\022\017\n\013MSG_SRC_GCS\020\001\022\022\n\016MSG_SRC"
    "_SERVER\020\002*6\n\007MsgLink\022\021\n\rMSG_LINK_MQTT\020\000\022"
    "\030\n\024MSG_LINK_SERIAL_PORT\020\001*\207\005\n\005MsgId\022\024\n\020M"
    "SG_ID_HEARTBEAT\020\000\022\032\n\026MSG_ID_CONNECT_REQU"
    "EST\020\001\022\033\n\027MSG_ID_CONNECT_RESPONSE\020\002\022\035\n\031MS"
    "G_ID_DISCONNECT_REQUEST\020\003\022\036\n\032MSG_ID_DISC"
    "ONNECT_RESPONSE\020\004\022\025\n\021MSG_ID_PARAM_ITEM\020\005"
    "\022\035\n\031MSG_ID_PARAM_READ_REQUEST\020\006\022\036\n\032MSG_I"
    "D_PARAM_READ_RESPONSE\020\007\022\036\n\032MSG_ID_PARAM_"
    "WRITE_REQUEST\020\010\022\037\n\033MSG_ID_PARAM_WRITE_RE"
    "SPONSE\020\t\022\027\n\023MSG_ID_MISSION_ITEM\020\n\022#\n\037MSG"
    "_ID_MISSION_DOWNLOAD_REQUEST\020\013\022$\n MSG_ID"
    "_MISSION_DOWNLOAD_RESPONSE\020\014\022!\n\035MSG_ID_M"
    "ISSION_UPLOAD_REQUEST\020\r\022\"\n\036MSG_ID_MISSIO"
    "N_UPLOAD_RESPONSE\020\016\022\032\n\026MSG_ID_MISSION_CU"
    "RRENT\020\017\022\036\n\032MSG_ID_MISSION_SET_CURRENT\020\020\022"
    " \n\034MSG_ID_MISSION_CLEAR_REQUEST\020\021\022!\n\035MSG"
    "_ID_MISSION_CLEAR_RESPONSE\020\022\022\031\n\025MSG_ID_B"
    "ATTERY_STATUS\020\023\022\022\n\016MSG_ID_COMMAND\020\024*W\n\005C"
    "mdId\022\027\n\023CMD_ID_NAV_WAYPOINT\020\000\022\032\n\026CMD_ID_"
    "DO_WEIGH_ANCHOR\020\001\022\031\n\025CMD_ID_DO_DROP_ANCH"
    "OR\020\002*\332\001\n\005Frame\022\020\n\014FRAME_GLOBAL\020\000\022\023\n\017FRAM"
    "E_LOCAL_NED\020\001\022\035\n\031FRAME_GLOBAL_RELATIVE_A"
    "LT\020\002\022\023\n\017FRAME_LOCAL_ENU\020\003\022\032\n\026FRAME_LOCAL"
    "_OFFSET_NED\020\004\022\034\n\030FRAME_GLOBAL_TERRAIN_AL"
    "T\020\005\022\022\n\016FRAME_BODY_FRD\020\006\022\023\n\017FRAME_LOCAL_F"
    "RD\020\007\022\023\n\017FRAME_LOCAL_FLU\020\010*\266\001\n\014MissionSta"
    "te\022\031\n\025MISSION_STATE_UNKNOWN\020\000\022\034\n\030MISSION"
    "_STATE_NO_MISSION\020\001\022\035\n\031MISSION_STATE_NOT"
    "_STARTED\020\002\022\030\n\024MISSION_STATE_ACTIVE\020\003\022\030\n\024"
    "MISSION_STATE_PAUSED\020\004\022\032\n\026MISSION_STATE_"
    "COMPLETE\020\005b\006proto3"
};
static ::absl::once_flag descriptor_table_msg_5fenum_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_msg_5fenum_2eproto = {
    false,
    false,
    1298,
    descriptor_table_protodef_msg_5fenum_2eproto,
    "msg_enum.proto",
    &descriptor_table_msg_5fenum_2eproto_once,
    nullptr,
    0,
    0,
    schemas,
    file_default_instances,
    TableStruct_msg_5fenum_2eproto::offsets,
    nullptr,
    file_level_enum_descriptors_msg_5fenum_2eproto,
    file_level_service_descriptors_msg_5fenum_2eproto,
};

// This function exists to be marked as weak.
// It can significantly speed up compilation by breaking up LLVM's SCC
// in the .pb.cc translation units. Large translation units see a
// reduction of more than 35% of walltime for optimized builds. Without
// the weak attribute all the messages in the file, including all the
// vtables and everything they use become part of the same SCC through
// a cycle like:
// GetMetadata -> descriptor table -> default instances ->
//   vtables -> GetMetadata
// By adding a weak function here we break the connection from the
// individual vtables back into the descriptor table.
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_msg_5fenum_2eproto_getter() {
  return &descriptor_table_msg_5fenum_2eproto;
}
// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2
static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_msg_5fenum_2eproto(&descriptor_table_msg_5fenum_2eproto);
namespace UsvLink {
const ::google::protobuf::EnumDescriptor* MsgSrc_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_msg_5fenum_2eproto);
  return file_level_enum_descriptors_msg_5fenum_2eproto[0];
}
PROTOBUF_CONSTINIT const uint32_t MsgSrc_internal_data_[] = {
    196608u, 0u, };
bool MsgSrc_IsValid(int value) {
  return 0 <= value && value <= 2;
}
const ::google::protobuf::EnumDescriptor* MsgLink_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_msg_5fenum_2eproto);
  return file_level_enum_descriptors_msg_5fenum_2eproto[1];
}
PROTOBUF_CONSTINIT const uint32_t MsgLink_internal_data_[] = {
    131072u, 0u, };
bool MsgLink_IsValid(int value) {
  return 0 <= value && value <= 1;
}
const ::google::protobuf::EnumDescriptor* MsgId_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_msg_5fenum_2eproto);
  return file_level_enum_descriptors_msg_5fenum_2eproto[2];
}
PROTOBUF_CONSTINIT const uint32_t MsgId_internal_data_[] = {
    1376256u, 0u, };
bool MsgId_IsValid(int value) {
  return 0 <= value && value <= 20;
}
const ::google::protobuf::EnumDescriptor* CmdId_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_msg_5fenum_2eproto);
  return file_level_enum_descriptors_msg_5fenum_2eproto[3];
}
PROTOBUF_CONSTINIT const uint32_t CmdId_internal_data_[] = {
    196608u, 0u, };
bool CmdId_IsValid(int value) {
  return 0 <= value && value <= 2;
}
const ::google::protobuf::EnumDescriptor* Frame_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_msg_5fenum_2eproto);
  return file_level_enum_descriptors_msg_5fenum_2eproto[4];
}
PROTOBUF_CONSTINIT const uint32_t Frame_internal_data_[] = {
    589824u, 0u, };
bool Frame_IsValid(int value) {
  return 0 <= value && value <= 8;
}
const ::google::protobuf::EnumDescriptor* MissionState_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_msg_5fenum_2eproto);
  return file_level_enum_descriptors_msg_5fenum_2eproto[5];
}
PROTOBUF_CONSTINIT const uint32_t MissionState_internal_data_[] = {
    393216u, 0u, };
bool MissionState_IsValid(int value) {
  return 0 <= value && value <= 5;
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace UsvLink
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
#include "google/protobuf/port_undef.inc"
