// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: msg_mission_download_response.proto

#include "msg_mission_download_response.pb.h"

#include <algorithm>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
#include "google/protobuf/generated_message_tctable_impl.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace UsvLink {

inline constexpr MissionDownloadResponse::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        mission_items_{},
        err_msg_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        ack_{0},
        opaque_id_{0} {}

template <typename>
PROTOBUF_CONSTEXPR MissionDownloadResponse::MissionDownloadResponse(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct MissionDownloadResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR MissionDownloadResponseDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~MissionDownloadResponseDefaultTypeInternal() {}
  union {
    MissionDownloadResponse _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 MissionDownloadResponseDefaultTypeInternal _MissionDownloadResponse_default_instance_;
}  // namespace UsvLink
static ::_pb::Metadata file_level_metadata_msg_5fmission_5fdownload_5fresponse_2eproto[1];
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_msg_5fmission_5fdownload_5fresponse_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_msg_5fmission_5fdownload_5fresponse_2eproto = nullptr;
const ::uint32_t TableStruct_msg_5fmission_5fdownload_5fresponse_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(
    protodesc_cold) = {
    PROTOBUF_FIELD_OFFSET(::UsvLink::MissionDownloadResponse, _impl_._has_bits_),
    PROTOBUF_FIELD_OFFSET(::UsvLink::MissionDownloadResponse, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::UsvLink::MissionDownloadResponse, _impl_.ack_),
    PROTOBUF_FIELD_OFFSET(::UsvLink::MissionDownloadResponse, _impl_.err_msg_),
    PROTOBUF_FIELD_OFFSET(::UsvLink::MissionDownloadResponse, _impl_.opaque_id_),
    PROTOBUF_FIELD_OFFSET(::UsvLink::MissionDownloadResponse, _impl_.mission_items_),
    ~0u,
    0,
    1,
    ~0u,
};

static const ::_pbi::MigrationSchema
    schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
        {0, 12, -1, sizeof(::UsvLink::MissionDownloadResponse)},
};

static const ::_pb::Message* const file_default_instances[] = {
    &::UsvLink::_MissionDownloadResponse_default_instance_._instance,
};
const char descriptor_table_protodef_msg_5fmission_5fdownload_5fresponse_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
    "\n#msg_mission_download_response.proto\022\007U"
    "svLink\032\026msg_mission_item.proto\"\233\001\n\027Missi"
    "onDownloadResponse\022\013\n\003ack\030\001 \001(\005\022\024\n\007err_m"
    "sg\030\002 \001(\tH\000\210\001\001\022\026\n\topaque_id\030\003 \001(\005H\001\210\001\001\022+\n"
    "\rmission_items\030\004 \003(\0132\024.UsvLink.MissionIt"
    "emB\n\n\010_err_msgB\014\n\n_opaque_idb\006proto3"
};
static const ::_pbi::DescriptorTable* const descriptor_table_msg_5fmission_5fdownload_5fresponse_2eproto_deps[1] =
    {
        &::descriptor_table_msg_5fmission_5fitem_2eproto,
};
static ::absl::once_flag descriptor_table_msg_5fmission_5fdownload_5fresponse_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_msg_5fmission_5fdownload_5fresponse_2eproto = {
    false,
    false,
    236,
    descriptor_table_protodef_msg_5fmission_5fdownload_5fresponse_2eproto,
    "msg_mission_download_response.proto",
    &descriptor_table_msg_5fmission_5fdownload_5fresponse_2eproto_once,
    descriptor_table_msg_5fmission_5fdownload_5fresponse_2eproto_deps,
    1,
    1,
    schemas,
    file_default_instances,
    TableStruct_msg_5fmission_5fdownload_5fresponse_2eproto::offsets,
    file_level_metadata_msg_5fmission_5fdownload_5fresponse_2eproto,
    file_level_enum_descriptors_msg_5fmission_5fdownload_5fresponse_2eproto,
    file_level_service_descriptors_msg_5fmission_5fdownload_5fresponse_2eproto,
};

// This function exists to be marked as weak.
// It can significantly speed up compilation by breaking up LLVM's SCC
// in the .pb.cc translation units. Large translation units see a
// reduction of more than 35% of walltime for optimized builds. Without
// the weak attribute all the messages in the file, including all the
// vtables and everything they use become part of the same SCC through
// a cycle like:
// GetMetadata -> descriptor table -> default instances ->
//   vtables -> GetMetadata
// By adding a weak function here we break the connection from the
// individual vtables back into the descriptor table.
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_msg_5fmission_5fdownload_5fresponse_2eproto_getter() {
  return &descriptor_table_msg_5fmission_5fdownload_5fresponse_2eproto;
}
// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2
static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_msg_5fmission_5fdownload_5fresponse_2eproto(&descriptor_table_msg_5fmission_5fdownload_5fresponse_2eproto);
namespace UsvLink {
// ===================================================================

class MissionDownloadResponse::_Internal {
 public:
  using HasBits = decltype(std::declval<MissionDownloadResponse>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
    8 * PROTOBUF_FIELD_OFFSET(MissionDownloadResponse, _impl_._has_bits_);
  static void set_has_err_msg(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
  static void set_has_opaque_id(HasBits* has_bits) {
    (*has_bits)[0] |= 2u;
  }
};

void MissionDownloadResponse::clear_mission_items() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.mission_items_.Clear();
}
MissionDownloadResponse::MissionDownloadResponse(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:UsvLink.MissionDownloadResponse)
}
inline PROTOBUF_NDEBUG_INLINE MissionDownloadResponse::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        mission_items_{visibility, arena, from.mission_items_},
        err_msg_(arena, from.err_msg_) {}

MissionDownloadResponse::MissionDownloadResponse(
    ::google::protobuf::Arena* arena,
    const MissionDownloadResponse& from)
    : ::google::protobuf::Message(arena) {
  MissionDownloadResponse* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);
  ::memcpy(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, ack_),
           reinterpret_cast<const char *>(&from._impl_) +
               offsetof(Impl_, ack_),
           offsetof(Impl_, opaque_id_) -
               offsetof(Impl_, ack_) +
               sizeof(Impl_::opaque_id_));

  // @@protoc_insertion_point(copy_constructor:UsvLink.MissionDownloadResponse)
}
inline PROTOBUF_NDEBUG_INLINE MissionDownloadResponse::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0},
        mission_items_{visibility, arena},
        err_msg_(arena) {}

inline void MissionDownloadResponse::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, ack_),
           0,
           offsetof(Impl_, opaque_id_) -
               offsetof(Impl_, ack_) +
               sizeof(Impl_::opaque_id_));
}
MissionDownloadResponse::~MissionDownloadResponse() {
  // @@protoc_insertion_point(destructor:UsvLink.MissionDownloadResponse)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void MissionDownloadResponse::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.err_msg_.Destroy();
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void MissionDownloadResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:UsvLink.MissionDownloadResponse)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.mission_items_.Clear();
  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    _impl_.err_msg_.ClearNonDefaultToEmpty();
  }
  _impl_.ack_ = 0;
  _impl_.opaque_id_ = 0;
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* MissionDownloadResponse::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 4, 1, 47, 2> MissionDownloadResponse::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(MissionDownloadResponse, _impl_._has_bits_),
    0, // no _extensions_
    4, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967280,  // skipmap
    offsetof(decltype(_table_), field_entries),
    4,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    &_MissionDownloadResponse_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    // repeated .UsvLink.MissionItem mission_items = 4;
    {::_pbi::TcParser::FastMtR1,
     {34, 63, 0, PROTOBUF_FIELD_OFFSET(MissionDownloadResponse, _impl_.mission_items_)}},
    // int32 ack = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(MissionDownloadResponse, _impl_.ack_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(MissionDownloadResponse, _impl_.ack_)}},
    // optional string err_msg = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 0, 0, PROTOBUF_FIELD_OFFSET(MissionDownloadResponse, _impl_.err_msg_)}},
    // optional int32 opaque_id = 3;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(MissionDownloadResponse, _impl_.opaque_id_), 1>(),
     {24, 1, 0, PROTOBUF_FIELD_OFFSET(MissionDownloadResponse, _impl_.opaque_id_)}},
  }}, {{
    65535, 65535
  }}, {{
    // int32 ack = 1;
    {PROTOBUF_FIELD_OFFSET(MissionDownloadResponse, _impl_.ack_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
    // optional string err_msg = 2;
    {PROTOBUF_FIELD_OFFSET(MissionDownloadResponse, _impl_.err_msg_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // optional int32 opaque_id = 3;
    {PROTOBUF_FIELD_OFFSET(MissionDownloadResponse, _impl_.opaque_id_), _Internal::kHasBitsOffset + 1, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
    // repeated .UsvLink.MissionItem mission_items = 4;
    {PROTOBUF_FIELD_OFFSET(MissionDownloadResponse, _impl_.mission_items_), -1, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kMessage | ::_fl::kTvTable)},
  }}, {{
    {::_pbi::TcParser::GetTable<::UsvLink::MissionItem>()},
  }}, {{
    "\37\0\7\0\0\0\0\0"
    "UsvLink.MissionDownloadResponse"
    "err_msg"
  }},
};

::uint8_t* MissionDownloadResponse::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:UsvLink.MissionDownloadResponse)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // int32 ack = 1;
  if (this->_internal_ack() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt32ToArrayWithField<1>(
            stream, this->_internal_ack(), target);
  }

  cached_has_bits = _impl_._has_bits_[0];
  // optional string err_msg = 2;
  if (cached_has_bits & 0x00000001u) {
    const std::string& _s = this->_internal_err_msg();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "UsvLink.MissionDownloadResponse.err_msg");
    target = stream->WriteStringMaybeAliased(2, _s, target);
  }

  // optional int32 opaque_id = 3;
  if (cached_has_bits & 0x00000002u) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt32ToArrayWithField<3>(
            stream, this->_internal_opaque_id(), target);
  }

  // repeated .UsvLink.MissionItem mission_items = 4;
  for (unsigned i = 0,
      n = static_cast<unsigned>(this->_internal_mission_items_size()); i < n; i++) {
    const auto& repfield = this->_internal_mission_items().Get(i);
    target = ::google::protobuf::internal::WireFormatLite::
        InternalWriteMessage(4, repfield, repfield.GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:UsvLink.MissionDownloadResponse)
  return target;
}

::size_t MissionDownloadResponse::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:UsvLink.MissionDownloadResponse)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .UsvLink.MissionItem mission_items = 4;
  total_size += 1UL * this->_internal_mission_items_size();
  for (const auto& msg : this->_internal_mission_items()) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSize(msg);
  }
  // optional string err_msg = 2;
  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_err_msg());
  }

  // int32 ack = 1;
  if (this->_internal_ack() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
        this->_internal_ack());
  }

  // optional int32 opaque_id = 3;
  if (cached_has_bits & 0x00000002u) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
        this->_internal_opaque_id());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData MissionDownloadResponse::_class_data_ = {
    MissionDownloadResponse::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* MissionDownloadResponse::GetClassData() const {
  return &_class_data_;
}

void MissionDownloadResponse::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<MissionDownloadResponse*>(&to_msg);
  auto& from = static_cast<const MissionDownloadResponse&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:UsvLink.MissionDownloadResponse)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_mission_items()->MergeFrom(
      from._internal_mission_items());
  if ((from._impl_._has_bits_[0] & 0x00000001u) != 0) {
    _this->_internal_set_err_msg(from._internal_err_msg());
  }
  if (from._internal_ack() != 0) {
    _this->_internal_set_ack(from._internal_ack());
  }
  if ((from._impl_._has_bits_[0] & 0x00000002u) != 0) {
    _this->_internal_set_opaque_id(from._internal_opaque_id());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void MissionDownloadResponse::CopyFrom(const MissionDownloadResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:UsvLink.MissionDownloadResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool MissionDownloadResponse::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* MissionDownloadResponse::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void MissionDownloadResponse::InternalSwap(MissionDownloadResponse* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  _impl_.mission_items_.InternalSwap(&other->_impl_.mission_items_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.err_msg_, &other->_impl_.err_msg_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(MissionDownloadResponse, _impl_.opaque_id_)
      + sizeof(MissionDownloadResponse::_impl_.opaque_id_)
      - PROTOBUF_FIELD_OFFSET(MissionDownloadResponse, _impl_.ack_)>(
          reinterpret_cast<char*>(&_impl_.ack_),
          reinterpret_cast<char*>(&other->_impl_.ack_));
}

::google::protobuf::Metadata MissionDownloadResponse::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_msg_5fmission_5fdownload_5fresponse_2eproto_getter, &descriptor_table_msg_5fmission_5fdownload_5fresponse_2eproto_once,
      file_level_metadata_msg_5fmission_5fdownload_5fresponse_2eproto[0]);
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace UsvLink
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
#include "google/protobuf/port_undef.inc"
