// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: msg_mission_item.proto

#include "msg_mission_item.pb.h"

#include <algorithm>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
#include "google/protobuf/generated_message_tctable_impl.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace UsvLink {

inline constexpr MissionItem::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        command_{nullptr},
        seq_{0},
        frame_{static_cast< ::UsvLink::Frame >(0)},
        current_{false},
        auto_continue_{false},
        x_{0},
        y_{0},
        z_{0} {}

template <typename>
PROTOBUF_CONSTEXPR MissionItem::MissionItem(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct MissionItemDefaultTypeInternal {
  PROTOBUF_CONSTEXPR MissionItemDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~MissionItemDefaultTypeInternal() {}
  union {
    MissionItem _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 MissionItemDefaultTypeInternal _MissionItem_default_instance_;
}  // namespace UsvLink
static ::_pb::Metadata file_level_metadata_msg_5fmission_5fitem_2eproto[1];
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_msg_5fmission_5fitem_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_msg_5fmission_5fitem_2eproto = nullptr;
const ::uint32_t TableStruct_msg_5fmission_5fitem_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(
    protodesc_cold) = {
    PROTOBUF_FIELD_OFFSET(::UsvLink::MissionItem, _impl_._has_bits_),
    PROTOBUF_FIELD_OFFSET(::UsvLink::MissionItem, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::UsvLink::MissionItem, _impl_.seq_),
    PROTOBUF_FIELD_OFFSET(::UsvLink::MissionItem, _impl_.frame_),
    PROTOBUF_FIELD_OFFSET(::UsvLink::MissionItem, _impl_.current_),
    PROTOBUF_FIELD_OFFSET(::UsvLink::MissionItem, _impl_.auto_continue_),
    PROTOBUF_FIELD_OFFSET(::UsvLink::MissionItem, _impl_.x_),
    PROTOBUF_FIELD_OFFSET(::UsvLink::MissionItem, _impl_.y_),
    PROTOBUF_FIELD_OFFSET(::UsvLink::MissionItem, _impl_.z_),
    PROTOBUF_FIELD_OFFSET(::UsvLink::MissionItem, _impl_.command_),
    ~0u,
    ~0u,
    ~0u,
    ~0u,
    ~0u,
    ~0u,
    ~0u,
    0,
};

static const ::_pbi::MigrationSchema
    schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
        {0, 16, -1, sizeof(::UsvLink::MissionItem)},
};

static const ::_pb::Message* const file_default_instances[] = {
    &::UsvLink::_MissionItem_default_instance_._instance,
};
const char descriptor_table_protodef_msg_5fmission_5fitem_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
    "\n\026msg_mission_item.proto\022\007UsvLink\032\016msg_e"
    "num.proto\032\021msg_command.proto\"\245\001\n\013Mission"
    "Item\022\013\n\003seq\030\001 \001(\005\022\035\n\005frame\030\002 \001(\0162\016.UsvLi"
    "nk.Frame\022\017\n\007current\030\003 \001(\010\022\025\n\rauto_contin"
    "ue\030\004 \001(\010\022\t\n\001x\030\005 \001(\002\022\t\n\001y\030\006 \001(\002\022\t\n\001z\030\007 \001("
    "\002\022!\n\007command\030\010 \001(\0132\020.UsvLink.Commandb\006pr"
    "oto3"
};
static const ::_pbi::DescriptorTable* const descriptor_table_msg_5fmission_5fitem_2eproto_deps[2] =
    {
        &::descriptor_table_msg_5fcommand_2eproto,
        &::descriptor_table_msg_5fenum_2eproto,
};
static ::absl::once_flag descriptor_table_msg_5fmission_5fitem_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_msg_5fmission_5fitem_2eproto = {
    false,
    false,
    244,
    descriptor_table_protodef_msg_5fmission_5fitem_2eproto,
    "msg_mission_item.proto",
    &descriptor_table_msg_5fmission_5fitem_2eproto_once,
    descriptor_table_msg_5fmission_5fitem_2eproto_deps,
    2,
    1,
    schemas,
    file_default_instances,
    TableStruct_msg_5fmission_5fitem_2eproto::offsets,
    file_level_metadata_msg_5fmission_5fitem_2eproto,
    file_level_enum_descriptors_msg_5fmission_5fitem_2eproto,
    file_level_service_descriptors_msg_5fmission_5fitem_2eproto,
};

// This function exists to be marked as weak.
// It can significantly speed up compilation by breaking up LLVM's SCC
// in the .pb.cc translation units. Large translation units see a
// reduction of more than 35% of walltime for optimized builds. Without
// the weak attribute all the messages in the file, including all the
// vtables and everything they use become part of the same SCC through
// a cycle like:
// GetMetadata -> descriptor table -> default instances ->
//   vtables -> GetMetadata
// By adding a weak function here we break the connection from the
// individual vtables back into the descriptor table.
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_msg_5fmission_5fitem_2eproto_getter() {
  return &descriptor_table_msg_5fmission_5fitem_2eproto;
}
// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2
static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_msg_5fmission_5fitem_2eproto(&descriptor_table_msg_5fmission_5fitem_2eproto);
namespace UsvLink {
// ===================================================================

class MissionItem::_Internal {
 public:
  using HasBits = decltype(std::declval<MissionItem>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
    8 * PROTOBUF_FIELD_OFFSET(MissionItem, _impl_._has_bits_);
  static const ::UsvLink::Command& command(const MissionItem* msg);
  static void set_has_command(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
};

const ::UsvLink::Command& MissionItem::_Internal::command(const MissionItem* msg) {
  return *msg->_impl_.command_;
}
void MissionItem::clear_command() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  if (_impl_.command_ != nullptr) _impl_.command_->Clear();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
MissionItem::MissionItem(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:UsvLink.MissionItem)
}
inline PROTOBUF_NDEBUG_INLINE MissionItem::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : _has_bits_{from._has_bits_},
        _cached_size_{0} {}

MissionItem::MissionItem(
    ::google::protobuf::Arena* arena,
    const MissionItem& from)
    : ::google::protobuf::Message(arena) {
  MissionItem* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);
  ::uint32_t cached_has_bits = _impl_._has_bits_[0];
  _impl_.command_ = (cached_has_bits & 0x00000001u)
                ? CreateMaybeMessage<::UsvLink::Command>(arena, *from._impl_.command_)
                : nullptr;
  ::memcpy(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, seq_),
           reinterpret_cast<const char *>(&from._impl_) +
               offsetof(Impl_, seq_),
           offsetof(Impl_, z_) -
               offsetof(Impl_, seq_) +
               sizeof(Impl_::z_));

  // @@protoc_insertion_point(copy_constructor:UsvLink.MissionItem)
}
inline PROTOBUF_NDEBUG_INLINE MissionItem::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void MissionItem::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, command_),
           0,
           offsetof(Impl_, z_) -
               offsetof(Impl_, command_) +
               sizeof(Impl_::z_));
}
MissionItem::~MissionItem() {
  // @@protoc_insertion_point(destructor:UsvLink.MissionItem)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void MissionItem::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  delete _impl_.command_;
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void MissionItem::Clear() {
// @@protoc_insertion_point(message_clear_start:UsvLink.MissionItem)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    ABSL_DCHECK(_impl_.command_ != nullptr);
    _impl_.command_->Clear();
  }
  ::memset(&_impl_.seq_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.z_) -
      reinterpret_cast<char*>(&_impl_.seq_)) + sizeof(_impl_.z_));
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* MissionItem::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<3, 8, 1, 0, 2> MissionItem::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(MissionItem, _impl_._has_bits_),
    0, // no _extensions_
    8, 56,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967040,  // skipmap
    offsetof(decltype(_table_), field_entries),
    8,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    &_MissionItem_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    // .UsvLink.Command command = 8;
    {::_pbi::TcParser::FastMtS1,
     {66, 0, 0, PROTOBUF_FIELD_OFFSET(MissionItem, _impl_.command_)}},
    // int32 seq = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(MissionItem, _impl_.seq_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(MissionItem, _impl_.seq_)}},
    // .UsvLink.Frame frame = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(MissionItem, _impl_.frame_), 63>(),
     {16, 63, 0, PROTOBUF_FIELD_OFFSET(MissionItem, _impl_.frame_)}},
    // bool current = 3;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(MissionItem, _impl_.current_), 63>(),
     {24, 63, 0, PROTOBUF_FIELD_OFFSET(MissionItem, _impl_.current_)}},
    // bool auto_continue = 4;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(MissionItem, _impl_.auto_continue_), 63>(),
     {32, 63, 0, PROTOBUF_FIELD_OFFSET(MissionItem, _impl_.auto_continue_)}},
    // float x = 5;
    {::_pbi::TcParser::FastF32S1,
     {45, 63, 0, PROTOBUF_FIELD_OFFSET(MissionItem, _impl_.x_)}},
    // float y = 6;
    {::_pbi::TcParser::FastF32S1,
     {53, 63, 0, PROTOBUF_FIELD_OFFSET(MissionItem, _impl_.y_)}},
    // float z = 7;
    {::_pbi::TcParser::FastF32S1,
     {61, 63, 0, PROTOBUF_FIELD_OFFSET(MissionItem, _impl_.z_)}},
  }}, {{
    65535, 65535
  }}, {{
    // int32 seq = 1;
    {PROTOBUF_FIELD_OFFSET(MissionItem, _impl_.seq_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
    // .UsvLink.Frame frame = 2;
    {PROTOBUF_FIELD_OFFSET(MissionItem, _impl_.frame_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kOpenEnum)},
    // bool current = 3;
    {PROTOBUF_FIELD_OFFSET(MissionItem, _impl_.current_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBool)},
    // bool auto_continue = 4;
    {PROTOBUF_FIELD_OFFSET(MissionItem, _impl_.auto_continue_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBool)},
    // float x = 5;
    {PROTOBUF_FIELD_OFFSET(MissionItem, _impl_.x_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kFloat)},
    // float y = 6;
    {PROTOBUF_FIELD_OFFSET(MissionItem, _impl_.y_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kFloat)},
    // float z = 7;
    {PROTOBUF_FIELD_OFFSET(MissionItem, _impl_.z_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kFloat)},
    // .UsvLink.Command command = 8;
    {PROTOBUF_FIELD_OFFSET(MissionItem, _impl_.command_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
  }}, {{
    {::_pbi::TcParser::GetTable<::UsvLink::Command>()},
  }}, {{
  }},
};

::uint8_t* MissionItem::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:UsvLink.MissionItem)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // int32 seq = 1;
  if (this->_internal_seq() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt32ToArrayWithField<1>(
            stream, this->_internal_seq(), target);
  }

  // .UsvLink.Frame frame = 2;
  if (this->_internal_frame() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
        2, this->_internal_frame(), target);
  }

  // bool current = 3;
  if (this->_internal_current() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(
        3, this->_internal_current(), target);
  }

  // bool auto_continue = 4;
  if (this->_internal_auto_continue() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(
        4, this->_internal_auto_continue(), target);
  }

  // float x = 5;
  static_assert(sizeof(::uint32_t) == sizeof(float),
                "Code assumes ::uint32_t and float are the same size.");
  float tmp_x = this->_internal_x();
  ::uint32_t raw_x;
  memcpy(&raw_x, &tmp_x, sizeof(tmp_x));
  if (raw_x != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(
        5, this->_internal_x(), target);
  }

  // float y = 6;
  static_assert(sizeof(::uint32_t) == sizeof(float),
                "Code assumes ::uint32_t and float are the same size.");
  float tmp_y = this->_internal_y();
  ::uint32_t raw_y;
  memcpy(&raw_y, &tmp_y, sizeof(tmp_y));
  if (raw_y != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(
        6, this->_internal_y(), target);
  }

  // float z = 7;
  static_assert(sizeof(::uint32_t) == sizeof(float),
                "Code assumes ::uint32_t and float are the same size.");
  float tmp_z = this->_internal_z();
  ::uint32_t raw_z;
  memcpy(&raw_z, &tmp_z, sizeof(tmp_z));
  if (raw_z != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(
        7, this->_internal_z(), target);
  }

  cached_has_bits = _impl_._has_bits_[0];
  // .UsvLink.Command command = 8;
  if (cached_has_bits & 0x00000001u) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        8, _Internal::command(this),
        _Internal::command(this).GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:UsvLink.MissionItem)
  return target;
}

::size_t MissionItem::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:UsvLink.MissionItem)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // .UsvLink.Command command = 8;
  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    total_size +=
        1 + ::google::protobuf::internal::WireFormatLite::MessageSize(*_impl_.command_);
  }

  // int32 seq = 1;
  if (this->_internal_seq() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
        this->_internal_seq());
  }

  // .UsvLink.Frame frame = 2;
  if (this->_internal_frame() != 0) {
    total_size += 1 +
                  ::_pbi::WireFormatLite::EnumSize(this->_internal_frame());
  }

  // bool current = 3;
  if (this->_internal_current() != 0) {
    total_size += 2;
  }

  // bool auto_continue = 4;
  if (this->_internal_auto_continue() != 0) {
    total_size += 2;
  }

  // float x = 5;
  static_assert(sizeof(::uint32_t) == sizeof(float),
                "Code assumes ::uint32_t and float are the same size.");
  float tmp_x = this->_internal_x();
  ::uint32_t raw_x;
  memcpy(&raw_x, &tmp_x, sizeof(tmp_x));
  if (raw_x != 0) {
    total_size += 5;
  }

  // float y = 6;
  static_assert(sizeof(::uint32_t) == sizeof(float),
                "Code assumes ::uint32_t and float are the same size.");
  float tmp_y = this->_internal_y();
  ::uint32_t raw_y;
  memcpy(&raw_y, &tmp_y, sizeof(tmp_y));
  if (raw_y != 0) {
    total_size += 5;
  }

  // float z = 7;
  static_assert(sizeof(::uint32_t) == sizeof(float),
                "Code assumes ::uint32_t and float are the same size.");
  float tmp_z = this->_internal_z();
  ::uint32_t raw_z;
  memcpy(&raw_z, &tmp_z, sizeof(tmp_z));
  if (raw_z != 0) {
    total_size += 5;
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData MissionItem::_class_data_ = {
    MissionItem::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* MissionItem::GetClassData() const {
  return &_class_data_;
}

void MissionItem::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<MissionItem*>(&to_msg);
  auto& from = static_cast<const MissionItem&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:UsvLink.MissionItem)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if ((from._impl_._has_bits_[0] & 0x00000001u) != 0) {
    _this->_internal_mutable_command()->::UsvLink::Command::MergeFrom(
        from._internal_command());
  }
  if (from._internal_seq() != 0) {
    _this->_internal_set_seq(from._internal_seq());
  }
  if (from._internal_frame() != 0) {
    _this->_internal_set_frame(from._internal_frame());
  }
  if (from._internal_current() != 0) {
    _this->_internal_set_current(from._internal_current());
  }
  if (from._internal_auto_continue() != 0) {
    _this->_internal_set_auto_continue(from._internal_auto_continue());
  }
  static_assert(sizeof(::uint32_t) == sizeof(float),
                "Code assumes ::uint32_t and float are the same size.");
  float tmp_x = from._internal_x();
  ::uint32_t raw_x;
  memcpy(&raw_x, &tmp_x, sizeof(tmp_x));
  if (raw_x != 0) {
    _this->_internal_set_x(from._internal_x());
  }
  static_assert(sizeof(::uint32_t) == sizeof(float),
                "Code assumes ::uint32_t and float are the same size.");
  float tmp_y = from._internal_y();
  ::uint32_t raw_y;
  memcpy(&raw_y, &tmp_y, sizeof(tmp_y));
  if (raw_y != 0) {
    _this->_internal_set_y(from._internal_y());
  }
  static_assert(sizeof(::uint32_t) == sizeof(float),
                "Code assumes ::uint32_t and float are the same size.");
  float tmp_z = from._internal_z();
  ::uint32_t raw_z;
  memcpy(&raw_z, &tmp_z, sizeof(tmp_z));
  if (raw_z != 0) {
    _this->_internal_set_z(from._internal_z());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void MissionItem::CopyFrom(const MissionItem& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:UsvLink.MissionItem)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool MissionItem::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* MissionItem::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void MissionItem::InternalSwap(MissionItem* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(MissionItem, _impl_.z_)
      + sizeof(MissionItem::_impl_.z_)
      - PROTOBUF_FIELD_OFFSET(MissionItem, _impl_.command_)>(
          reinterpret_cast<char*>(&_impl_.command_),
          reinterpret_cast<char*>(&other->_impl_.command_));
}

::google::protobuf::Metadata MissionItem::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_msg_5fmission_5fitem_2eproto_getter, &descriptor_table_msg_5fmission_5fitem_2eproto_once,
      file_level_metadata_msg_5fmission_5fitem_2eproto[0]);
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace UsvLink
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
#include "google/protobuf/port_undef.inc"
