// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: msg_param_read_request.proto

#include "msg_param_read_request.pb.h"

#include <algorithm>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
#include "google/protobuf/generated_message_tctable_impl.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace UsvLink {

inline constexpr ParamReadRequest::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : param_id_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        param_index_{0},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR ParamReadRequest::ParamReadRequest(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct ParamReadRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ParamReadRequestDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~ParamReadRequestDefaultTypeInternal() {}
  union {
    ParamReadRequest _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ParamReadRequestDefaultTypeInternal _ParamReadRequest_default_instance_;
}  // namespace UsvLink
static ::_pb::Metadata file_level_metadata_msg_5fparam_5fread_5frequest_2eproto[1];
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_msg_5fparam_5fread_5frequest_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_msg_5fparam_5fread_5frequest_2eproto = nullptr;
const ::uint32_t TableStruct_msg_5fparam_5fread_5frequest_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(
    protodesc_cold) = {
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::UsvLink::ParamReadRequest, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::UsvLink::ParamReadRequest, _impl_.param_id_),
    PROTOBUF_FIELD_OFFSET(::UsvLink::ParamReadRequest, _impl_.param_index_),
};

static const ::_pbi::MigrationSchema
    schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::UsvLink::ParamReadRequest)},
};

static const ::_pb::Message* const file_default_instances[] = {
    &::UsvLink::_ParamReadRequest_default_instance_._instance,
};
const char descriptor_table_protodef_msg_5fparam_5fread_5frequest_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
    "\n\034msg_param_read_request.proto\022\007UsvLink\""
    "9\n\020ParamReadRequest\022\020\n\010param_id\030\001 \001(\t\022\023\n"
    "\013param_index\030\002 \001(\005b\006proto3"
};
static ::absl::once_flag descriptor_table_msg_5fparam_5fread_5frequest_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_msg_5fparam_5fread_5frequest_2eproto = {
    false,
    false,
    106,
    descriptor_table_protodef_msg_5fparam_5fread_5frequest_2eproto,
    "msg_param_read_request.proto",
    &descriptor_table_msg_5fparam_5fread_5frequest_2eproto_once,
    nullptr,
    0,
    1,
    schemas,
    file_default_instances,
    TableStruct_msg_5fparam_5fread_5frequest_2eproto::offsets,
    file_level_metadata_msg_5fparam_5fread_5frequest_2eproto,
    file_level_enum_descriptors_msg_5fparam_5fread_5frequest_2eproto,
    file_level_service_descriptors_msg_5fparam_5fread_5frequest_2eproto,
};

// This function exists to be marked as weak.
// It can significantly speed up compilation by breaking up LLVM's SCC
// in the .pb.cc translation units. Large translation units see a
// reduction of more than 35% of walltime for optimized builds. Without
// the weak attribute all the messages in the file, including all the
// vtables and everything they use become part of the same SCC through
// a cycle like:
// GetMetadata -> descriptor table -> default instances ->
//   vtables -> GetMetadata
// By adding a weak function here we break the connection from the
// individual vtables back into the descriptor table.
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_msg_5fparam_5fread_5frequest_2eproto_getter() {
  return &descriptor_table_msg_5fparam_5fread_5frequest_2eproto;
}
// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2
static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_msg_5fparam_5fread_5frequest_2eproto(&descriptor_table_msg_5fparam_5fread_5frequest_2eproto);
namespace UsvLink {
// ===================================================================

class ParamReadRequest::_Internal {
 public:
};

ParamReadRequest::ParamReadRequest(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:UsvLink.ParamReadRequest)
}
inline PROTOBUF_NDEBUG_INLINE ParamReadRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : param_id_(arena, from.param_id_),
        _cached_size_{0} {}

ParamReadRequest::ParamReadRequest(
    ::google::protobuf::Arena* arena,
    const ParamReadRequest& from)
    : ::google::protobuf::Message(arena) {
  ParamReadRequest* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);
  _impl_.param_index_ = from._impl_.param_index_;

  // @@protoc_insertion_point(copy_constructor:UsvLink.ParamReadRequest)
}
inline PROTOBUF_NDEBUG_INLINE ParamReadRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : param_id_(arena),
        _cached_size_{0} {}

inline void ParamReadRequest::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.param_index_ = {};
}
ParamReadRequest::~ParamReadRequest() {
  // @@protoc_insertion_point(destructor:UsvLink.ParamReadRequest)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void ParamReadRequest::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.param_id_.Destroy();
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void ParamReadRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:UsvLink.ParamReadRequest)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.param_id_.ClearToEmpty();
  _impl_.param_index_ = 0;
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* ParamReadRequest::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 41, 2> ParamReadRequest::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_ParamReadRequest_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    // int32 param_index = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(ParamReadRequest, _impl_.param_index_), 63>(),
     {16, 63, 0, PROTOBUF_FIELD_OFFSET(ParamReadRequest, _impl_.param_index_)}},
    // string param_id = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(ParamReadRequest, _impl_.param_id_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string param_id = 1;
    {PROTOBUF_FIELD_OFFSET(ParamReadRequest, _impl_.param_id_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // int32 param_index = 2;
    {PROTOBUF_FIELD_OFFSET(ParamReadRequest, _impl_.param_index_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
  }},
  // no aux_entries
  {{
    "\30\10\0\0\0\0\0\0"
    "UsvLink.ParamReadRequest"
    "param_id"
  }},
};

::uint8_t* ParamReadRequest::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:UsvLink.ParamReadRequest)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // string param_id = 1;
  if (!this->_internal_param_id().empty()) {
    const std::string& _s = this->_internal_param_id();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "UsvLink.ParamReadRequest.param_id");
    target = stream->WriteStringMaybeAliased(1, _s, target);
  }

  // int32 param_index = 2;
  if (this->_internal_param_index() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt32ToArrayWithField<2>(
            stream, this->_internal_param_index(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:UsvLink.ParamReadRequest)
  return target;
}

::size_t ParamReadRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:UsvLink.ParamReadRequest)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string param_id = 1;
  if (!this->_internal_param_id().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_param_id());
  }

  // int32 param_index = 2;
  if (this->_internal_param_index() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
        this->_internal_param_index());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData ParamReadRequest::_class_data_ = {
    ParamReadRequest::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* ParamReadRequest::GetClassData() const {
  return &_class_data_;
}

void ParamReadRequest::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<ParamReadRequest*>(&to_msg);
  auto& from = static_cast<const ParamReadRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:UsvLink.ParamReadRequest)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_param_id().empty()) {
    _this->_internal_set_param_id(from._internal_param_id());
  }
  if (from._internal_param_index() != 0) {
    _this->_internal_set_param_index(from._internal_param_index());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void ParamReadRequest::CopyFrom(const ParamReadRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:UsvLink.ParamReadRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool ParamReadRequest::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* ParamReadRequest::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void ParamReadRequest::InternalSwap(ParamReadRequest* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.param_id_, &other->_impl_.param_id_, arena);
        swap(_impl_.param_index_, other->_impl_.param_index_);
}

::google::protobuf::Metadata ParamReadRequest::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_msg_5fparam_5fread_5frequest_2eproto_getter, &descriptor_table_msg_5fparam_5fread_5frequest_2eproto_once,
      file_level_metadata_msg_5fparam_5fread_5frequest_2eproto[0]);
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace UsvLink
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
#include "google/protobuf/port_undef.inc"
